analytics:
  google_id: ''

baseURL: ''

languageCode: en-us

footnoteBacklinkSymbol: '↩'

biblioFormat: short # short | long

bylineFormat: name-title # name | name-title | false

citations:
  pageLocationDivider: ', '
  popupStyle: text # text | icon

enableSearch: true

figures:
  enableModal: true
  enableZoom: true
  labelPosition: on-top # below | on-top

i18n:
  en:
    biblioHeading: Bibliography
    nextPageButton: Next
    objectLinkText: View in Collection
    pageLabelDivider: '. '
    prevPageButton: Back

menu: list # brief | list
