baseURL: ''
languageCode: en-us
footnoteBacklinkSymbol: '↩'
GoogleAnalytics:
  id: ''

biblioFormat: short # short | long
bylineFormat: name-title # name | name-title | false

citations:
  pageLocationDivider: ', '
  popupStyle: text # text | icon

enableSearch: true

figures:
  enableModal: true
  enableZoom: true
  labelLocation: on-top # below | on-top

localizedLabels:
  en:
    biblioHeading: Bibliography
    nextPageButton: Next
    objectLinkText: View in Collection
    pageLabelDivider: '. '
    prevPageButton: Back

menu: list # brief | list
