analytics:
  googleId: ''

baseURL: ''

footnotes:
  backlinkSymbol: '↩'

bibliography:
  format: short # short | long

byline:
  format: name-title # name | name-title | false

citations:
  format: Chicago # Chicago | MLA
  popupStyle: text # text | icon

figures:
  enableModal: true
  enableZoom: true
  labelPosition: on-top # below | on-top

localization:
  defaultLocale: en-us
  labels:
    en:
      biblioHeading: Bibliography
      nextPageButton: Next
      objectLinkText: View in Collection
      pageLabelDivider: '. '
      prevPageButton: Back

menu: list # brief | list

search:
  enabled: true
