version: 2.1

orbs:
  node: circleci/node@4.2.1

anchors:
  - &workspace_root ~/
  - &attach_workspace
    attach_workspace:
      at: *workspace_root
  - &docker_image
    docker:
      - image: circleci/buildpack-deps:trusty
        user: root
  # - &npm_cache_key cache1-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  checkout:
    <<: *docker_image
    steps:
      - checkout
      - persist_to_workspace:
          root: *workspace_root
          paths: .
  install_dependencies:
    <<: *docker_image
    steps:
      - *attach_workspace
      - run:
          name: Add temporary download directory
          command: mkdir -p /tmp
      - run:
          name: Install Prince XML
          command: |
            wget -q -O /tmp/prince.deb https://www.princexml.com/download/prince_12.5-1_ubuntu14.04_amd64.deb
            dpkg -i /tmp/prince.deb
            rm /tmp/prince.deb
      - run:
          name: Install Pandoc
          command: |
            wget -q -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
            dpkg -i /tmp/pandoc.deb
            rm /tmp/pandoc.deb
      # - run: 
      #     name: [todo] install kindle previewer
      - persist_to_workspace:
          root: *workspace_root
          paths: .
  build_install_cli:
    <<: *docker_image
    steps:
      - *attach_workspace
      - node/install
      # - restore_cache:
      #     keys:
      #       - *npm_cache_key
      - run:
          name: Install CLI dependencies
          command: cd packages/cli && npm install
      - run:
          name: Build CLI
          command: cd packages/cli && npm run build
      - run:
          name: Install CLI
          command: cd packages/cli && npm install -g
      - persist_to_workspace:
          root: *workspace_root
          paths: .
      # - save_cache:
      #     key: *npm_cache_key
          # paths:
          #   - node_modules
          #   - ~/.npm
          #   - ~/.cache
  test:
    <<: *docker_image
    steps:
      - *attach_workspace
      - node/install
      # - add_ssh_keys:
      #     fingerprints:
      #       - "8a:6d:63:75:61:e8:02:ec:0b:e6:75:58:ab:d1:01:cd"
      - run:
          name: Add test report directory
          command: mkdir -p ~/test-results
      - run:
          name: Run Quire Commands Test
          command: cd packages/cli && npm run test cli.test.js
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  install_build_test:
    jobs:
      - checkout
      - install_dependencies
      - build_install_cli:
          requires:
            - checkout
            - install_dependencies
      - test:
          requires:
            - build_install_cli