version: 2.1

anchors:
  - &workspace_root ~/project
  - &attach_workspace
    attach_workspace:
      at: *workspace_root
  - &docker_image
    docker:
      - image: circleci/buildpack-deps:trusty
        user: root
  - &npm_cache_key dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  install_dependencies:
    <<: *docker_image
    steps:
      - run:
          name: Install Node and NPM
          command: |
            set +e             
            touch $BASH_ENV  
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --lts
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Add temporary download directory
          command: mkdir -p /tmp
      - run:
          name: Install Prince XML
          command: |
            wget -q -O /tmp/prince.deb https://www.princexml.com/download/prince_12.5-1_ubuntu14.04_amd64.deb
            dpkg -i /tmp/prince.deb
            rm /tmp/prince.deb
      - run:
          name: Install Pandoc
          command: |
            wget -q -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
            dpkg -i /tmp/pandoc.deb
            rm /tmp/pandoc.deb
      # - run: 
      #     name: [todo] install kindle previewer
  build:
    <<: *docker_image
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Build and install the Quire CLI
          command: npm run cli:install
      - persist_to_workspace:
          root: *workspace_root
          paths: .
      - save_cache:
          key: *npm_cache_key
          paths:
            - node_modules
            - ~/.cache
            - ~/.npm
  test:
    <<: *docker_image
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
            - *npm_cache_key
      - run:
          name: Add test report directory
          command: mkdir -p ~/test-results
      - run:
          name: Run Quire Commands Test
          command: cd packages/cli && npm run test cli.test.js
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  install_build_test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - build